/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DigitalTwinRouteImport } from './routes/digital-twin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoDrizzleRouteImport } from './routes/demo/drizzle'
import { Route as DemoBetterAuthRouteImport } from './routes/demo/better-auth'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'
import { Route as ApiUnitySaveObjectDotdoRouteImport } from './routes/api/unity/saveObject[.]do'
import { Route as ApiUnityLoadObjectsDotdoRouteImport } from './routes/api/unity/loadObjects[.]do'
import { Route as ApiUnityLoadObjectDotdoRouteImport } from './routes/api/unity/loadObject[.]do'
import { Route as ApiUnityDeleteObjectDotdoRouteImport } from './routes/api/unity/deleteObject[.]do'
import { Route as ApiUnityAssetCatalogDotdoRouteImport } from './routes/api/unity/assetCatalog[.]do'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalTwinRoute = DigitalTwinRouteImport.update({
  id: '/digital-twin',
  path: '/digital-twin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDrizzleRoute = DemoDrizzleRouteImport.update({
  id: '/demo/drizzle',
  path: '/demo/drizzle',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoBetterAuthRoute = DemoBetterAuthRouteImport.update({
  id: '/demo/better-auth',
  path: '/demo/better-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUnitySaveObjectDotdoRoute = ApiUnitySaveObjectDotdoRouteImport.update({
  id: '/api/unity/saveObject.do',
  path: '/api/unity/saveObject.do',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUnityLoadObjectsDotdoRoute =
  ApiUnityLoadObjectsDotdoRouteImport.update({
    id: '/api/unity/loadObjects.do',
    path: '/api/unity/loadObjects.do',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiUnityLoadObjectDotdoRoute = ApiUnityLoadObjectDotdoRouteImport.update({
  id: '/api/unity/loadObject.do',
  path: '/api/unity/loadObject.do',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUnityDeleteObjectDotdoRoute =
  ApiUnityDeleteObjectDotdoRouteImport.update({
    id: '/api/unity/deleteObject.do',
    path: '/api/unity/deleteObject.do',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiUnityAssetCatalogDotdoRoute =
  ApiUnityAssetCatalogDotdoRouteImport.update({
    id: '/api/unity/assetCatalog.do',
    path: '/api/unity/assetCatalog.do',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/unity/assetCatalog.do': typeof ApiUnityAssetCatalogDotdoRoute
  '/api/unity/deleteObject.do': typeof ApiUnityDeleteObjectDotdoRoute
  '/api/unity/loadObject.do': typeof ApiUnityLoadObjectDotdoRoute
  '/api/unity/loadObjects.do': typeof ApiUnityLoadObjectsDotdoRoute
  '/api/unity/saveObject.do': typeof ApiUnitySaveObjectDotdoRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/unity/assetCatalog.do': typeof ApiUnityAssetCatalogDotdoRoute
  '/api/unity/deleteObject.do': typeof ApiUnityDeleteObjectDotdoRoute
  '/api/unity/loadObject.do': typeof ApiUnityLoadObjectDotdoRoute
  '/api/unity/loadObjects.do': typeof ApiUnityLoadObjectsDotdoRoute
  '/api/unity/saveObject.do': typeof ApiUnitySaveObjectDotdoRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/unity/assetCatalog.do': typeof ApiUnityAssetCatalogDotdoRoute
  '/api/unity/deleteObject.do': typeof ApiUnityDeleteObjectDotdoRoute
  '/api/unity/loadObject.do': typeof ApiUnityLoadObjectDotdoRoute
  '/api/unity/loadObjects.do': typeof ApiUnityLoadObjectsDotdoRoute
  '/api/unity/saveObject.do': typeof ApiUnitySaveObjectDotdoRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/digital-twin'
    | '/login'
    | '/register'
    | '/settings'
    | '/demo/better-auth'
    | '/demo/drizzle'
    | '/demo/tanstack-query'
    | '/api/auth/$'
    | '/api/unity/assetCatalog.do'
    | '/api/unity/deleteObject.do'
    | '/api/unity/loadObject.do'
    | '/api/unity/loadObjects.do'
    | '/api/unity/saveObject.do'
    | '/demo/form/address'
    | '/demo/form/simple'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard'
    | '/digital-twin'
    | '/login'
    | '/register'
    | '/settings'
    | '/demo/better-auth'
    | '/demo/drizzle'
    | '/demo/tanstack-query'
    | '/api/auth/$'
    | '/api/unity/assetCatalog.do'
    | '/api/unity/deleteObject.do'
    | '/api/unity/loadObject.do'
    | '/api/unity/loadObjects.do'
    | '/api/unity/saveObject.do'
    | '/demo/form/address'
    | '/demo/form/simple'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/digital-twin'
    | '/login'
    | '/register'
    | '/settings'
    | '/demo/better-auth'
    | '/demo/drizzle'
    | '/demo/tanstack-query'
    | '/api/auth/$'
    | '/api/unity/assetCatalog.do'
    | '/api/unity/deleteObject.do'
    | '/api/unity/loadObject.do'
    | '/api/unity/loadObjects.do'
    | '/api/unity/saveObject.do'
    | '/demo/form/address'
    | '/demo/form/simple'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRoute
  DigitalTwinRoute: typeof DigitalTwinRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  DemoBetterAuthRoute: typeof DemoBetterAuthRoute
  DemoDrizzleRoute: typeof DemoDrizzleRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiUnityAssetCatalogDotdoRoute: typeof ApiUnityAssetCatalogDotdoRoute
  ApiUnityDeleteObjectDotdoRoute: typeof ApiUnityDeleteObjectDotdoRoute
  ApiUnityLoadObjectDotdoRoute: typeof ApiUnityLoadObjectDotdoRoute
  ApiUnityLoadObjectsDotdoRoute: typeof ApiUnityLoadObjectsDotdoRoute
  ApiUnitySaveObjectDotdoRoute: typeof ApiUnitySaveObjectDotdoRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-twin': {
      id: '/digital-twin'
      path: '/digital-twin'
      fullPath: '/digital-twin'
      preLoaderRoute: typeof DigitalTwinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/drizzle': {
      id: '/demo/drizzle'
      path: '/demo/drizzle'
      fullPath: '/demo/drizzle'
      preLoaderRoute: typeof DemoDrizzleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/better-auth': {
      id: '/demo/better-auth'
      path: '/demo/better-auth'
      fullPath: '/demo/better-auth'
      preLoaderRoute: typeof DemoBetterAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/unity/saveObject.do': {
      id: '/api/unity/saveObject.do'
      path: '/api/unity/saveObject.do'
      fullPath: '/api/unity/saveObject.do'
      preLoaderRoute: typeof ApiUnitySaveObjectDotdoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/unity/loadObjects.do': {
      id: '/api/unity/loadObjects.do'
      path: '/api/unity/loadObjects.do'
      fullPath: '/api/unity/loadObjects.do'
      preLoaderRoute: typeof ApiUnityLoadObjectsDotdoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/unity/loadObject.do': {
      id: '/api/unity/loadObject.do'
      path: '/api/unity/loadObject.do'
      fullPath: '/api/unity/loadObject.do'
      preLoaderRoute: typeof ApiUnityLoadObjectDotdoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/unity/deleteObject.do': {
      id: '/api/unity/deleteObject.do'
      path: '/api/unity/deleteObject.do'
      fullPath: '/api/unity/deleteObject.do'
      preLoaderRoute: typeof ApiUnityDeleteObjectDotdoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/unity/assetCatalog.do': {
      id: '/api/unity/assetCatalog.do'
      path: '/api/unity/assetCatalog.do'
      fullPath: '/api/unity/assetCatalog.do'
      preLoaderRoute: typeof ApiUnityAssetCatalogDotdoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRoute,
  DigitalTwinRoute: DigitalTwinRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  DemoBetterAuthRoute: DemoBetterAuthRoute,
  DemoDrizzleRoute: DemoDrizzleRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiUnityAssetCatalogDotdoRoute: ApiUnityAssetCatalogDotdoRoute,
  ApiUnityDeleteObjectDotdoRoute: ApiUnityDeleteObjectDotdoRoute,
  ApiUnityLoadObjectDotdoRoute: ApiUnityLoadObjectDotdoRoute,
  ApiUnityLoadObjectsDotdoRoute: ApiUnityLoadObjectsDotdoRoute,
  ApiUnitySaveObjectDotdoRoute: ApiUnitySaveObjectDotdoRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
